//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bug_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTHoaDon = new HashSet<CTHoaDon>();
        }
    
        public int IdPro { get; set; }
        public string NamePro { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> Price { get; set; }
        public string Descriptions { get; set; }
        public string ImagePath { get; set; }
        public Nullable<short> IdCate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDon> CTHoaDon { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
